In [1]:
# Import the usual libraries and variables.
%run standard_imports.py

# Install a pip package in the current Jupyter kernel.
import sys
!{sys.executable} -m pip install --user pypika

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: pypika in /home/rachel/.local/lib/python2.7/site-packages (0.27.1)
Requirement already satisfied: aenum==2.1.2 in /home/rachel/.local/lib/python2.7/site-packages (from pypika) (2.1.2)

In [2]:
import datetime
from pypika import MySQLQuery, Table, Order, functions as fn

start_date = datetime.date(2019, 1, 1)
end_date = datetime.date(2020, 1, 1)

charge = Table("charge")
merchant_app_charge = Table("merchant_app_charge")
merchant_app = Table("merchant_app")
developer_app = Table("developer_app")
developer = Table("developer")

gross_revenue = (fn.Sum(charge.amount)/100).as_("gross_revenue")
gross_developer_portion = (fn.Sum(fn.Coalesce(charge.developer_portion,
                                             charge.amount * 0.7))/100).as_("gross_developer_portion")
gross_clover_portion = (fn.Sum(charge.amount - fn.Coalesce(charge.developer_portion,
                                                          charge.amount * 0.7))/100).as_("gross_clover_portion")

q = MySQLQuery.from_(charge).join(
    merchant_app_charge
).on(
    merchant_app_charge.charge_id == charge.id 
).join(
    merchant_app
).on(
    merchant_app.id == merchant_app_charge.merchant_app_id
).join(
    developer_app
).on(
    developer_app.id == merchant_app.app_id
).join(
    developer
).on(
    developer.id == developer_app.developer_id
).select(
    developer.uuid,
    developer.name,
    gross_revenue,
    gross_developer_portion,
    gross_clover_portion
).where(
    (developer.name != "Clover") &
    (developer.is_rev_share_flat_rate == 0)
).where(
    (charge.system_type == "INFOLEASE") &
    (charge.status.isin(["DISBURSED", "BILLED"])) &
    (charge.currency == "USD")
).where(
    charge.created_time[start_date:end_date]
).groupby(developer.id) \
.orderby(gross_clover_portion, order=Order.desc)

query = q.get_sql()
print(query)

db = Db("~/.clover/p801.cfg")
df = pd.read_sql(query, con=db.conn)
db.close()

df

SELECT `developer`.`uuid`,`developer`.`name`,SUM(`charge`.`amount`)/100 `gross_revenue`,SUM(COALESCE(`charge`.`developer_portion`,`charge`.`amount`*0.7))/100 `gross_developer_portion`,SUM(`charge`.`amount`-COALESCE(`charge`.`developer_portion`,`charge`.`amount`*0.7))/100 `gross_clover_portion` FROM `charge` JOIN `merchant_app_charge` ON `merchant_app_charge`.`charge_id`=`charge`.`id` JOIN `merchant_app` ON `merchant_app`.`id`=`merchant_app_charge`.`merchant_app_id` JOIN `developer_app` ON `developer_app`.`id`=`merchant_app`.`app_id` JOIN `developer` ON `developer`.`id`=`developer_app`.`developer_id` WHERE `developer`.`name`<>'Clover' AND `developer`.`is_rev_share_flat_rate`=0 AND `charge`.`system_type`='INFOLEASE' AND `charge`.`status` IN ('DISBURSED','BILLED') AND `charge`.`currency`='USD' AND `charge`.`created_time` BETWEEN '2019-01-01' AND '2020-01-01' GROUP BY `developer`.`id` ORDER BY `gross_clover_portion` DESC

,uuid,name,gross_revenue,gross_developer_portion,gross_clover_portion
0,2SW5NA5C30G10,Homebase,772430.64,540797.147,231633.493
1,R9XNECD2A8VKP,Infuse,462994.22,324121.314,138872.906
2,3GVN1P855JXEA,Abreeze Technology,457940.13,320648.962,137291.168
3,DK22NG4RNCM7W,Seven Spaces,412933.44,289260.850,123672.590
4,QCRD5T0ZX1HSG,DAVO Technologies,306448.02,214545.219,91902.801
5,DJJ1DMZS8AP42,Menufy,238006.25,166608.020,71398.230
6,1Z9K2PP9WGRKT,"Shopventory, Inc.",187454.37,131218.614,56235.756
7,H0MPC0J3SVFY6,4 Leaf Labs,183747.84,128645.473,55102.367
8,DF48AHKSK0A94,TapMango Inc.,166243.63,116370.730,49872.900
9,FXP6KXWMEVCB4,Zaytech,163615.10,114552.667,49062.433
10,ZAQ9DE6JAH7JJ,Loyalzoo,128254.04,89783.453,38470.587
11,5CQY9KWKPC76M,"Appheaven, LLC",116811.63,81819.467,34992.163
12,3D5NXQRNKZB60,Qualia,107369.64,75186.655,32182.985
13,GPEXAC0X05QRC,Sku IQ,103209.10,72246.538,30962.562
14,S8Q6CDK5HFZNG,SPS,97963.84,68587.635,29376.205
15,X6MH48WMNTPWM,eCard Systems INC,85679.77,59989.216,25690.554
16,956TEQ2SD2E4M,BuyFi,64307.15,45019.817,19287.333
17,11HKHSC6QK3A6,InvoiceASAP,62907.72,44035.906,18871.814
18,ES6D6X7EJGGAG,"Zoomifi, Inc",62412.24,43735.425,18676.815
19,TPHEXD0BRVNYJ,ITsoft,53558.82,37499.655,16059.165
20,935Q6J6BZJVVJ,Rewards Labs,46453.40,32521.406,13931.994
21,Z64XHS51QG7QY,Ecwid Inc.,43677.27,30574.262,13103.008
22,1FEBRN2RGAS66,Customer Connect LLC,32515.30,22763.748,9751.552
23,QQH2N8WJM1RW8,Trezoro,29874.92,20912.538,8962.382
24,4KNX79GQ7S090,Yellow Dog Software,28138.96,19697.300,8441.660
25,FED8WCXBGTWG2,LoyLap,27912.98,19540.039,8372.941
26,S4T3B9YGFDCZ2,Simple POS,26099.48,18275.782,7823.698
27,E7GDSMH9C0ZP0,Factor4,24859.08,17401.646,7457.434
28,03SBFMTAF4YDT,KIPOS LABS INC,22678.66,15876.647,6802.013
29,R163FJH5NSTDA,Apptizer Inc.,20744.88,14523.095,6221.785
...,...,...,...,...,...
119,866K6W3T4TP32,FiveStars,290.00,203.000,87.000
120,781P98NEZXYCA,Aperture,274.65,192.255,82.395
121,057CR3R8EHYM4,"Dynamic Digital Advertising, LLC.",271.04,189.803,81.237
122,G7GQBJR54812G,TexasBrokers,252.66,177.121,75.539
123,XRHWY6KVYM3WR,OwnerListens,241.94,169.360,72.580
124,MZSDV86W996Z0,Tattle,200.00,140.000,60.000
125,PD1S0T5HH2W1G,Kingdon,199.92,139.979,59.941
126,PRWMJVVNJJT7W,Avalon Ridge Technologies,199.75,139.840,59.910
127,WKHVQWR0VFWNC,Woolton,182.63,127.848,54.782
128,T98HZ1XP1Q18A,Noster Mobile,156.93,109.930,47.000
129,KPT59Y3BM8BE8,Jing Huang,152.36,106.854,45.506
130,R7HAYPF3CNKHT,Giftboard LLC,150.00,105.000,45.000
131,T06VK4AP9KGV2,Movylo,149.75,104.840,44.910
132,ZBVCS7KH702QR,Matthew Gaines,149.70,104.923,44.777
133,BRTX61H6E24SP,Magic Money,138.68,97.080,41.600
134,7EH9ECQ0P2XC8,Coin Out Inc,129.92,90.986,38.934
135,743HVR9T2MADC,Abreeze Technology,129.20,90.482,38.718
136,KF81C1KESKYYE,K3 Software Corp,125.00,87.500,37.500
137,B1W57N38KWQBW,appilee,125.73,88.550,37.180
138,ST0GZEJ0RM5MG,Colligso,121.61,85.130,36.480
139,X6N2F2VHK5REJ,NuOrder Technologies,100.00,70.000,30.000
140,2JK0B8MAX1S4J,Invenstar,99.95,69.965,29.985
141,RZKJ74JTXV8DR,Turnkey Processing,56.29,39.403,16.887
142,J2DG1N0HVY25E,Parker,53.28,37.310,15.970
143,A6FHQ3YQ2BVWA,Recurability,48.65,34.055,14.595
144,D2HGBST781DGW,StaffedUp,45.43,31.801,13.629
145,ZTG3WM9543CWA,Boppl Ltd,45.00,31.500,13.500
146,MCNWSAJF9RVY6,BankTech LLC,43.25,30.359,12.891
147,M6TAH8QZVF6WG,AppVoyage,23.96,16.800,7.160
148,Y4ZEV7WM7VPP2,"CreditStaff, LLC",5.35,3.760,1.590

In [3]:
import datetime
import calendar

def annualize_ytd(value):
    current = datetime.datetime.now()
    day_of_year = current.timetuple().tm_yday
    total_days = 366 if calendar.isleap(current.year) else 365
    year_progress = float(day_of_year)/float(total_days)
    return value/year_progress

df["annualized_gross_revenue"] = df["gross_revenue"].map(lambda x: round(annualize_ytd(x)))
df

,uuid,name,gross_revenue,gross_developer_portion,gross_clover_portion,annualized_gross_revenue
0,2SW5NA5C30G10,Homebase,772430.64,540797.147,231633.493,2104009.0
1,R9XNECD2A8VKP,Infuse,462994.22,324121.314,138872.906,1261141.0
2,3GVN1P855JXEA,Abreeze Technology,457940.13,320648.962,137291.168,1247374.0
3,DK22NG4RNCM7W,Seven Spaces,412933.44,289260.850,123672.590,1124781.0
4,QCRD5T0ZX1HSG,DAVO Technologies,306448.02,214545.219,91902.801,834728.0
5,DJJ1DMZS8AP42,Menufy,238006.25,166608.020,71398.230,648301.0
6,1Z9K2PP9WGRKT,"Shopventory, Inc.",187454.37,131218.614,56235.756,510603.0
7,H0MPC0J3SVFY6,4 Leaf Labs,183747.84,128645.473,55102.367,500507.0
8,DF48AHKSK0A94,TapMango Inc.,166243.63,116370.730,49872.900,452828.0
9,FXP6KXWMEVCB4,Zaytech,163615.10,114552.667,49062.433,445668.0
10,ZAQ9DE6JAH7JJ,Loyalzoo,128254.04,89783.453,38470.587,349349.0
11,5CQY9KWKPC76M,"Appheaven, LLC",116811.63,81819.467,34992.163,318181.0
12,3D5NXQRNKZB60,Qualia,107369.64,75186.655,32182.985,292462.0
13,GPEXAC0X05QRC,Sku IQ,103209.10,72246.538,30962.562,281129.0
14,S8Q6CDK5HFZNG,SPS,97963.84,68587.635,29376.205,266842.0
15,X6MH48WMNTPWM,eCard Systems INC,85679.77,59989.216,25690.554,233381.0
16,956TEQ2SD2E4M,BuyFi,64307.15,45019.817,19287.333,175165.0
17,11HKHSC6QK3A6,InvoiceASAP,62907.72,44035.906,18871.814,171353.0
18,ES6D6X7EJGGAG,"Zoomifi, Inc",62412.24,43735.425,18676.815,170003.0
19,TPHEXD0BRVNYJ,ITsoft,53558.82,37499.655,16059.165,145888.0
20,935Q6J6BZJVVJ,Rewards Labs,46453.40,32521.406,13931.994,126534.0
21,Z64XHS51QG7QY,Ecwid Inc.,43677.27,30574.262,13103.008,118972.0
22,1FEBRN2RGAS66,Customer Connect LLC,32515.30,22763.748,9751.552,88568.0
23,QQH2N8WJM1RW8,Trezoro,29874.92,20912.538,8962.382,81376.0
24,4KNX79GQ7S090,Yellow Dog Software,28138.96,19697.300,8441.660,76647.0
25,FED8WCXBGTWG2,LoyLap,27912.98,19540.039,8372.941,76032.0
26,S4T3B9YGFDCZ2,Simple POS,26099.48,18275.782,7823.698,71092.0
27,E7GDSMH9C0ZP0,Factor4,24859.08,17401.646,7457.434,67713.0
28,03SBFMTAF4YDT,KIPOS LABS INC,22678.66,15876.647,6802.013,61774.0
29,R163FJH5NSTDA,Apptizer Inc.,20744.88,14523.095,6221.785,56507.0
...,...,...,...,...,...,...
119,866K6W3T4TP32,FiveStars,290.00,203.000,87.000,790.0
120,781P98NEZXYCA,Aperture,274.65,192.255,82.395,748.0
121,057CR3R8EHYM4,"Dynamic Digital Advertising, LLC.",271.04,189.803,81.237,738.0
122,G7GQBJR54812G,TexasBrokers,252.66,177.121,75.539,688.0
123,XRHWY6KVYM3WR,OwnerListens,241.94,169.360,72.580,659.0
124,MZSDV86W996Z0,Tattle,200.00,140.000,60.000,545.0
125,PD1S0T5HH2W1G,Kingdon,199.92,139.979,59.941,545.0
126,PRWMJVVNJJT7W,Avalon Ridge Technologies,199.75,139.840,59.910,544.0
127,WKHVQWR0VFWNC,Woolton,182.63,127.848,54.782,497.0
128,T98HZ1XP1Q18A,Noster Mobile,156.93,109.930,47.000,427.0
129,KPT59Y3BM8BE8,Jing Huang,152.36,106.854,45.506,415.0
130,R7HAYPF3CNKHT,Giftboard LLC,150.00,105.000,45.000,409.0
131,T06VK4AP9KGV2,Movylo,149.75,104.840,44.910,408.0
132,ZBVCS7KH702QR,Matthew Gaines,149.70,104.923,44.777,408.0
133,BRTX61H6E24SP,Magic Money,138.68,97.080,41.600,378.0
134,7EH9ECQ0P2XC8,Coin Out Inc,129.92,90.986,38.934,354.0
135,743HVR9T2MADC,Abreeze Technology,129.20,90.482,38.718,352.0
136,KF81C1KESKYYE,K3 Software Corp,125.00,87.500,37.500,340.0
137,B1W57N38KWQBW,appilee,125.73,88.550,37.180,342.0
138,ST0GZEJ0RM5MG,Colligso,121.61,85.130,36.480,331.0
139,X6N2F2VHK5REJ,NuOrder Technologies,100.00,70.000,30.000,272.0
140,2JK0B8MAX1S4J,Invenstar,99.95,69.965,29.985,272.0
141,RZKJ74JTXV8DR,Turnkey Processing,56.29,39.403,16.887,153.0
142,J2DG1N0HVY25E,Parker,53.28,37.310,15.970,145.0
143,A6FHQ3YQ2BVWA,Recurability,48.65,34.055,14.595,133.0
144,D2HGBST781DGW,StaffedUp,45.43,31.801,13.629,124.0
145,ZTG3WM9543CWA,Boppl Ltd,45.00,31.500,13.500,123.0
146,MCNWSAJF9RVY6,BankTech LLC,43.25,30.359,12.891,118.0
147,M6TAH8QZVF6WG,AppVoyage,23.96,16.800,7.160,65.0
148,Y4ZEV7WM7VPP2,"CreditStaff, LLC",5.35,3.760,1.590,15.0

In [4]:
DIAMOND_REV_THRESHOLD = 2400000
GOLD_REV_THRESHOLD    =  600000
SILVER_REV_THRESHOLD  =  250000
BRONZE_REV_THRESHOLD  =   50000

def categorize_by_rev(value):
    if value > DIAMOND_REV_THRESHOLD:
        return "Diamond"
    if value > GOLD_REV_THRESHOLD:
        return "Gold"
    if value > SILVER_REV_THRESHOLD:
        return "Silver"
    if value > BRONZE_REV_THRESHOLD:
        return "Bronze"
    else:
        return "Public"


df["support_tier"] = df["annualized_gross_revenue"].map(lambda x: categorize_by_rev(x))
df

,uuid,name,gross_revenue,gross_developer_portion,gross_clover_portion,annualized_gross_revenue,support_tier
0,2SW5NA5C30G10,Homebase,772430.64,540797.147,231633.493,2104009.0,Gold
1,R9XNECD2A8VKP,Infuse,462994.22,324121.314,138872.906,1261141.0,Gold
2,3GVN1P855JXEA,Abreeze Technology,457940.13,320648.962,137291.168,1247374.0,Gold
3,DK22NG4RNCM7W,Seven Spaces,412933.44,289260.850,123672.590,1124781.0,Gold
4,QCRD5T0ZX1HSG,DAVO Technologies,306448.02,214545.219,91902.801,834728.0,Gold
5,DJJ1DMZS8AP42,Menufy,238006.25,166608.020,71398.230,648301.0,Gold
6,1Z9K2PP9WGRKT,"Shopventory, Inc.",187454.37,131218.614,56235.756,510603.0,Silver
7,H0MPC0J3SVFY6,4 Leaf Labs,183747.84,128645.473,55102.367,500507.0,Silver
8,DF48AHKSK0A94,TapMango Inc.,166243.63,116370.730,49872.900,452828.0,Silver
9,FXP6KXWMEVCB4,Zaytech,163615.10,114552.667,49062.433,445668.0,Silver
10,ZAQ9DE6JAH7JJ,Loyalzoo,128254.04,89783.453,38470.587,349349.0,Silver
11,5CQY9KWKPC76M,"Appheaven, LLC",116811.63,81819.467,34992.163,318181.0,Silver
12,3D5NXQRNKZB60,Qualia,107369.64,75186.655,32182.985,292462.0,Silver
13,GPEXAC0X05QRC,Sku IQ,103209.10,72246.538,30962.562,281129.0,Silver
14,S8Q6CDK5HFZNG,SPS,97963.84,68587.635,29376.205,266842.0,Silver
15,X6MH48WMNTPWM,eCard Systems INC,85679.77,59989.216,25690.554,233381.0,Bronze
16,956TEQ2SD2E4M,BuyFi,64307.15,45019.817,19287.333,175165.0,Bronze
17,11HKHSC6QK3A6,InvoiceASAP,62907.72,44035.906,18871.814,171353.0,Bronze
18,ES6D6X7EJGGAG,"Zoomifi, Inc",62412.24,43735.425,18676.815,170003.0,Bronze
19,TPHEXD0BRVNYJ,ITsoft,53558.82,37499.655,16059.165,145888.0,Bronze
20,935Q6J6BZJVVJ,Rewards Labs,46453.40,32521.406,13931.994,126534.0,Bronze
21,Z64XHS51QG7QY,Ecwid Inc.,43677.27,30574.262,13103.008,118972.0,Bronze
22,1FEBRN2RGAS66,Customer Connect LLC,32515.30,22763.748,9751.552,88568.0,Bronze
23,QQH2N8WJM1RW8,Trezoro,29874.92,20912.538,8962.382,81376.0,Bronze
24,4KNX79GQ7S090,Yellow Dog Software,28138.96,19697.300,8441.660,76647.0,Bronze
25,FED8WCXBGTWG2,LoyLap,27912.98,19540.039,8372.941,76032.0,Bronze
26,S4T3B9YGFDCZ2,Simple POS,26099.48,18275.782,7823.698,71092.0,Bronze
27,E7GDSMH9C0ZP0,Factor4,24859.08,17401.646,7457.434,67713.0,Bronze
28,03SBFMTAF4YDT,KIPOS LABS INC,22678.66,15876.647,6802.013,61774.0,Bronze
29,R163FJH5NSTDA,Apptizer Inc.,20744.88,14523.095,6221.785,56507.0,Bronze
...,...,...,...,...,...,...,...
119,866K6W3T4TP32,FiveStars,290.00,203.000,87.000,790.0,Public
120,781P98NEZXYCA,Aperture,274.65,192.255,82.395,748.0,Public
121,057CR3R8EHYM4,"Dynamic Digital Advertising, LLC.",271.04,189.803,81.237,738.0,Public
122,G7GQBJR54812G,TexasBrokers,252.66,177.121,75.539,688.0,Public
123,XRHWY6KVYM3WR,OwnerListens,241.94,169.360,72.580,659.0,Public
124,MZSDV86W996Z0,Tattle,200.00,140.000,60.000,545.0,Public
125,PD1S0T5HH2W1G,Kingdon,199.92,139.979,59.941,545.0,Public
126,PRWMJVVNJJT7W,Avalon Ridge Technologies,199.75,139.840,59.910,544.0,Public
127,WKHVQWR0VFWNC,Woolton,182.63,127.848,54.782,497.0,Public
128,T98HZ1XP1Q18A,Noster Mobile,156.93,109.930,47.000,427.0,Public
129,KPT59Y3BM8BE8,Jing Huang,152.36,106.854,45.506,415.0,Public
130,R7HAYPF3CNKHT,Giftboard LLC,150.00,105.000,45.000,409.0,Public
131,T06VK4AP9KGV2,Movylo,149.75,104.840,44.910,408.0,Public
132,ZBVCS7KH702QR,Matthew Gaines,149.70,104.923,44.777,408.0,Public
133,BRTX61H6E24SP,Magic Money,138.68,97.080,41.600,378.0,Public
134,7EH9ECQ0P2XC8,Coin Out Inc,129.92,90.986,38.934,354.0,Public
135,743HVR9T2MADC,Abreeze Technology,129.20,90.482,38.718,352.0,Public
136,KF81C1KESKYYE,K3 Software Corp,125.00,87.500,37.500,340.0,Public
137,B1W57N38KWQBW,appilee,125.73,88.550,37.180,342.0,Public
138,ST0GZEJ0RM5MG,Colligso,121.61,85.130,36.480,331.0,Public
139,X6N2F2VHK5REJ,NuOrder Technologies,100.00,70.000,30.000,272.0,Public
140,2JK0B8MAX1S4J,Invenstar,99.95,69.965,29.985,272.0,Public
141,RZKJ74JTXV8DR,Turnkey Processing,56.29,39.403,16.887,153.0,Public
142,J2DG1N0HVY25E,Parker,53.28,37.310,15.970,145.0,Public
143,A6FHQ3YQ2BVWA,Recurability,48.65,34.055,14.595,133.0,Public
144,D2HGBST781DGW,StaffedUp,45.43,31.801,13.629,124.0,Public
145,ZTG3WM9543CWA,Boppl Ltd,45.00,31.500,13.500,123.0,Public
146,MCNWSAJF9RVY6,BankTech LLC,43.25,30.359,12.891,118.0,Public
147,M6TAH8QZVF6WG,AppVoyage,23.96,16.800,7.160,65.0,Public
148,Y4ZEV7WM7VPP2,"CreditStaff, LLC",5.35,3.760,1.590,15.0,Public